/**
 * Emits `mcp-servers.config.json` from the TypeScript registry so the two can
 * never drift. Run `pnpm generate:mcp`; `pnpm check` verifies the committed
 * file is current.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { AGENTS } from "../src/agents/index.ts";
import { MCP_REGISTRY } from "../src/mcpRegistry.ts";

export function buildConfig(): unknown {
  const bindings: Record<string, { mcpServers: string[]; skills: string[] }> =
    {};
  for (const agent of AGENTS) {
    bindings[agent.id] = {
      mcpServers: [...agent.mcpServers],
      skills: [...agent.skills],
    };
  }

  return {
    $comment:
      "GENERATED by scripts/generate-mcp-config.mts from src/mcpRegistry.ts. Do not edit by hand. This is a declarative registry, NOT the executable .mcp.json.",
    version: 1,
    servers: MCP_REGISTRY.map((server) => ({
      id: server.id,
      displayName: server.displayName,
      category: server.category,
      kind: server.kind,
      description: server.description,
      endpoint: server.endpoint,
      defaultPermissions: [...server.defaultPermissions],
      tools: [...server.tools],
      requiredEnv: [...server.requiredEnv],
      scopes: [...server.scopes],
      provisioned: server.provisioned,
    })),
    agentBindings: bindings,
  };
}

export const OUTPUT_PATH: string = join(
  import.meta.dirname,
  "..",
  "mcp-servers.config.json",
);

export function serialize(): string {
  return `${JSON.stringify(buildConfig(), null, 2)}\n`;
}

if (process.argv[1] === import.meta.filename) {
  writeFileSync(OUTPUT_PATH, serialize());
  console.log(`wrote ${OUTPUT_PATH}`);
}
